# frozen_string_literal: true

require "teek"
require "teek/sdl2"
require_relative "mgba/runtime"
require_relative "mgba/child_window"
require_relative "mgba/tip_service"
require_relative "mgba/settings_window"
require_relative "mgba/rom_info_window"
require_relative "mgba/save_state_picker"
require_relative "mgba/save_state_manager"
require_relative "mgba/toast_overlay"
require_relative "mgba/overlay_renderer"
require_relative "mgba/input_mappings"
require_relative "mgba/hotkey_map"
require_relative "mgba/recorder"
require_relative "mgba/player"
